/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.artigosesportivos.view;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author nicolly.crsouza
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        abrirPDV = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        abrirClientes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        abrirProdutos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        abrirRelatorios = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        abrirSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/output-onlinepngtools.png"))); // NOI18N

        jMenu1.setText("Ponto de Venda");

        abrirPDV.setText("Abrir");
        abrirPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPDVActionPerformed(evt);
            }
        });
        jMenu1.add(abrirPDV);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Clientes");

        abrirClientes.setText("Abrir");
        abrirClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirClientesActionPerformed(evt);
            }
        });
        jMenu2.add(abrirClientes);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Produtos");

        abrirProdutos.setText("Abrir");
        abrirProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirProdutosActionPerformed(evt);
            }
        });
        jMenu3.add(abrirProdutos);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Relatórios");

        abrirRelatorios.setText("Abrir");
        abrirRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirRelatoriosActionPerformed(evt);
            }
        });
        jMenu4.add(abrirRelatorios);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Sobre");

        abrirSobre.setText("Abrir");
        abrirSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirSobreActionPerformed(evt);
            }
        });
        jMenu5.add(abrirSobre);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(logo)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(logo)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPDVActionPerformed
        PontodeVenda pdv = new PontodeVenda();
        pdv.setVisible(true);
    }//GEN-LAST:event_abrirPDVActionPerformed

    private void abrirClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirClientesActionPerformed
        ClienteView cliente = null;
        try {
            cliente = new ClienteView();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        cliente.setVisible(true);
    }//GEN-LAST:event_abrirClientesActionPerformed

    private void abrirProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirProdutosActionPerformed
        ProdutoView produto = new ProdutoView();
        produto.setVisible(true);
    }//GEN-LAST:event_abrirProdutosActionPerformed

    private void abrirRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirRelatoriosActionPerformed
        RelatorioSintetico relatorioSintetico = new RelatorioSintetico();
        relatorioSintetico.setVisible(true);
    }//GEN-LAST:event_abrirRelatoriosActionPerformed

    private void abrirSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirSobreActionPerformed
        Sobre sobre = new Sobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_abrirSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirClientes;
    private javax.swing.JMenuItem abrirPDV;
    private javax.swing.JMenuItem abrirProdutos;
    private javax.swing.JMenuItem abrirRelatorios;
    private javax.swing.JMenuItem abrirSobre;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
